### ISSUE TITLE
Screen Mounting/Orientation Issue

### ISSUE THREAD

**Issue by hoofta** [geaz/simplyRetro-Z5#2]
I finally got all my components in, I printed the pieces and started your project! I followed your instructions about making sure I knew which was "up" was on the screen and what I received was opposite of yours. Unfortunately, this has now lead to the electronics mount being backward and the 5mm FPV HDMI Adapter to be too short. I don't know if there is a way for future builders to find this out before they purchase the screen. If the electronics board can be flipped where the pi zero is mounted on the left, and battery as well as the powerboard on the right, then I should be able to proceed just fine. I might be able to do some swapping/altering on the electronic board but I was figuring it might be quicker if you could flip it since you designed it.

This could all be fixed to if there was a rotate screen 180º command. This would then pose a problem for me since I've already cut my screw mounts on the screen, however, it would save a lot of hassle for future builds.

**Comment by geaz** [comment]
Do you have a picture of you screen PCB? Would be really strange, if they produce it in different rotations. 

The screen can be rotated in the config.txt. Per default I already rotated it by 180°, because I assembled my screen upside down. As you can see here: https://raw.githubusercontent.com/geaz/simplyRetro-Z5/master/images/3.jpg

**Comment by hoofta** [comment]
Circles provided for perspective
![Uploading 2019-07-03 16.58.10.jpg…]()
![Uploading 2019-07-03 16.58.40.jpg…]()

**Comment by geaz** [comment]
Ok, I see the problem. The screen seems to be ok. You just cutted the wrong mounts :)
Please look again at this picture: https://raw.githubusercontent.com/geaz/simplyRetro-Z5/master/images/3.jpg

The display gets mounted in the shell rotated by 180°.

I hoped my phrasing in the description "The display will be assembled upside down" and the picture would be enough to make it clear.

**Comment by hoofta** [comment]
When I read "the display will be assembled upside down I saw that as it was upside down in the frame as it was being built. I now see what you are saying that it is mean to be installed upside to be rotated within the R.pi. Thanks for taking to explain it.

**Comment by geaz** [comment]
Ah I see why my description was misleading. I tried to rephrase it. Hopefully this makes it easier to understand for following makers. Thank you!
