### ISSUE TITLE
Add WiFi configuration menu

### ISSUE THREAD

**Issue by janzev** [geaz/simplyRetro-Z5#3]
I didn't build this now but I will do it as soosn as possible.

I have an idea which could improve your handheld:
Make wifi configurable through the gui, maybe a settings menu.
If this is not possible it would be very nice if the sd slot could be reachable from the outside (maybe a sd extension cable and a hole in the outer shell.

**Comment by geaz** [comment]
Hi!

A external accessible sd slot is planed for my next iteration of this handheld. But I don't know when I will have the time to work on it, because at the moment I am in the process of designing a "little brother" (3 inch display).

But I will check, if I can make the wifi configurable.

**Comment by janzev** [comment]
After posting the issue I thought about possibilites making wifi configurable. 

You can start other applications through emulationstation if you add another tab. I thought about a little python (or similar) script with a qtGui (qtGui has a virtual keyboard element which could maybe be useable with the console buttons) that lists all available wifi SSIDs and has a textbox for entering the wifi key. If the touchscreen is connected to the pi it could also maybe be used with touch input. Unfortunately a touchscreen doesn't support the retro feeling that this console should have.

If wifi configurable I wouldn't need a SD slot. But a SD slot which is independent from the boot sd card could be the best solution.

**Comment by batorni** [comment]
I think I'll work on adding this feature tonight or this weekend. I've noticed some performance issues, and I'm almost sure its due to wifi being enabled 24/7

**Comment by geaz** [comment]
Why should we create a "custom" application for it and include it into the system list?

Wouldn't it be really great to add it to the emulation menu itself? The one which comes up, if you press 'start'.
THis shouldn't be to hard. The 'GuiMenu.cpp' in emulation station contains the whole menu and it would be easy to add a custom entry for simplyRetro. Would be really cool I think.

At the moment I am thinking about two menu entries for the custom menu:
- WiFi Enabled (yes, no)
- FTP enabled (yes, no)

Anything else?

**Comment by janzev** [comment]
Like mentioned above I think it would be great to configure the WiFi completely through the menu (searching for WiFi networks and entering the password).

**Comment by geaz** [comment]
What do you think?

https://streamable.com/1jgjp

Have to do a bit more things, but it looks promising.
I took the onscreen keyboard from Recalbox and modified it a bit to work with the retropie emulation station version, which simplyRetro is using.

**Comment by batorni** [comment]
That's lookin' real good! better than my quick idea :)

**Comment by janzev** [comment]
Looks great!

**Comment by geaz** [comment]
Feature complete now. I will create a new release soon :)
