### ISSUE TITLE
 Z5 custom distribution failed

### ISSUE THREAD

**Issue by GarGamel55** [geaz/simplyRetro-Z5#4]
Hello,
I am very interested in this project !

I printed the pieces and started the electronics. The powering circuit is working ([like here](https://i.imgur.com/bwuunFP.jpg)), but when loading the distribution, it crashes and the Z5 stops (because GPIO19 ?). If I stay press the start button, I can read the error messages ([see photo](https://framapic.org/v2I3r6XNd5pk/qZ1MtVyPF16N.jpg))

I tried with several SD card and 2 different software (Etcher and a linux utilty) and also V1 and V1.1, same results.

You have an idea?

**Comment by geaz** [comment]
Hi!

Could you please delete the file "retropower.cfg" from the boot partition and then start it again? This is necessary to test, if the "power script" is the source of failure?

**Comment by GarGamel55** [comment]
Thank you Geaz for the quick return :)

It seems that this file is the problem. Now I go to the welcome screen to configure the gamepad.

The retropower.cfg file indicates the Wiring Pi pin "24" of the GPIO 19, which is normal.

**Comment by geaz** [comment]
Ok, that confirms my assumption, i guess. It seems, that the "problem" here is, that you don't have the second circuit ready yet. Is this right? As soon as your second circuit (the one with the ADC), is connected the power script should work. Just readd the "retropower.cfg", when you made progress.

I will change the script for the future to be able to switch these functionalities on and off for testing purposes. Thanks!

**Comment by GarGamel55** [comment]
Hello,
I mounted all the electronics parts (except the buttons to Pi), but the problem comes back with the file "retropower.cfg".
I checked the diagrams several times, everything seems ok. :(

**Comment by geaz** [comment]
Hi,
to bad it does not work, but lets try to fix this together :)
First of all let me recap the current situation (please tell me, if anything in this recap is wrong) and ask a few questions:

In your first post you mentioned that your power button is working - that is, you are able to start the pi by pressing the button, and the pi stays on until the system crashes.

Did you wire both circuits on the exact same GPIOs mentioned in the diagrams?
Are you able to take a picture of you ADC circuit (front and back)?

> I have a doubt, the ground of the "powering circuit" goes to the ground of powerboost 1000 or that of Pi Zero?

Both should work fine.

**Comment by GarGamel55** [comment]
> In your first post you mentioned that your power button is working - that is, you are able to start the pi by pressing the button, and the pi stays on until the system crashes.

Yes, that's it and the Pi stops after 10-15 seconds (just after the logo "retrograme" with writing "terminated" at the top left of the screen).
But if I keep pressing the button, the pi don't stops and I can see the error messages as in the picture in my first post. When I release the button the Pi stops.

When i remove the retropower.cfg file, it can see the screen to configure the buttons.

I will recheck all the welds and my circuit and come back to you quickly.

thank you so much

**Comment by GarGamel55** [comment]
Here are some pictures of my electronics:

[Overview](https://framapic.org/hzbZn2fxDr7l/2xkCJP4dasvY.jpg)
[PI](https://framapic.org/PFTIJ0a4r163/XcRMH0b8j9j7.jpg)
[Power Circuit (front)](https://framapic.org/UYfxIdOfmI79/TipgXj4LW3WQ.jpg)
[Power Circuit (back)](https://framapic.org/3DWpAMG75geb/bHV2m3KwqWGJ.jpg)

PS : I removed the SD Card to check files, it's normal that the sd slot is empty

**Comment by geaz** [comment]
First of all, cool color :)

On a first glance the circuits seem to be ok.
I changed the retroPower tool in such a way now, that the different features can be turned off. Furthermore I added logging to a file. Please use the new release 1.3 to reflash your SD card, if possible.

Look into the boot partition and do a backup of the file retroPower.cfg.
After this please change the configuration like in the following two examples. On each change turn the device on. And rerun the test with the next configuration.
Please tell me with which configuration the device "crashed" and with which configuration it didn't. Furthermore please attach the "retroPower-log.txt" from the boot partition. I hope we can then find the problem :)

Config 1:
```
[features]
shutdown = true     
batCheck = false    

[pins]
shutdown = 24       

[debug]
active = true      
writeLog = true    
onlyReadAdc = false 
```

Config 2
```
[features]
shutdown = false     
batCheck = true    

[pins]
shutdown = 24       

[debug]
active = true      
writeLog = true    
onlyReadAdc = true 
```

**Comment by GarGamel55** [comment]
> First of all, cool color :)
It's my children's choice :)

I found the problem (by chance) !!!  When I took the pictures I ripped the powerboost wires (those of the BAT / Lipo pin) and I had to sold them again.

In testing the 3 config above, I had no crash ! So I flashed the previous version to compare and .... no more crashes. The problem was a bad welding on the powerboost (ADC not correctly powered)

 I'm confused for the time lost (but I'm happy to be able to continue the project)

Thanks a lot :)

**Comment by geaz** [comment]
Nice! Glad it works now!
Was a nice opportunity to add the additional options to the retropower tool ;)

Will close the issues then.
