### ISSUE TITLE
Enhancement - Enable SSH

### ISSUE THREAD

**Issue by batorni** [geaz/simplyRetro-Z5#8]
I haven't dove into how BuildRoot works, but adding the option for SSH would be very nice to help make this easier to modify once the pi is closed up.

It looks like you can just add openssh when you run 'make menuconfig' but I haven't gotten a full dev environment up an running yet to try this out.

**Comment by geaz** [comment]
It would really help, yes. I left it out, because in my tests it always bloated the boot time. Not just by a few seconds, but tenth of seconds....

Maybe I can test this again with an option to deactivate it in the new menu :)

Will come back to you soon.

**Comment by geaz** [comment]
Added dropbear SSH server and a option do activate/deavtivate it to the new menu in emulation station. Will create a new release soon :)
